# Generated by Django 4.1.3 on 2022-11-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='edu_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobdescription',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='max_salary',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(null=True),
        ),
    ]
