# Generated by Django 4.1.3 on 2022-11-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_candidate_country_candidate_edu_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_des',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
