# Generated by Django 4.1.3 on 2022-11-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_company_company_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
