# Generated by Django 4.1.3 on 2022-11-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
