# Generated by Django 4.1.3 on 2022-11-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_jobdetails_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='logo_pic',
            field=models.ImageField(null=True, upload_to='app/img/company'),
        ),
    ]
