# Generated by Django 4.1.3 on 2022-11-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_jobdetails_logo_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='companyaddress',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
