# Generated by Django 4.1.3 on 2022-11-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_usermaster_time_st'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='is_active',
        ),
    ]
