# Generated by Django 4.1.3 on 2022-11-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_applylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applylist',
            old_name='can',
            new_name='candidate_id',
        ),
        migrations.RenameField(
            model_name='applylist',
            old_name='job',
            new_name='job_id',
        ),
    ]
