# Generated by Django 4.1.3 on 2022-11-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_can_applylist_candidate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='dob',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='edu_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='jobdescription',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
